version: "1" # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
  - .git
  - .venv
  - data/*

rule_settings:
  enable:
    - default
    - gpsg
  disable: ["docstrings-for-functions"]
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false
