[project]
name = "merriam-api-parser"
version = "0.1.0"
description = "A parser for the Merriam-Webster API"
authors = [{ name = "Zhengbo Wang", email = "lw7205675@gmail.com" }]
dependencies = ["ruff", "black", "mypy", "pylint"]
requires-python = ">=3.11"

[tool.ruff]
select = ["ALL"]
ignore = [
  # Will raise for untyped "self", this is not needed for the time being
  # https://github.com/charliermarsh/ruff/issues/1231#issuecomment-1350066198
  "ANN101",
]
line-length = 88
target-version = "py311"
fix = true
fixable = ["ALL"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.black]
target-version = ['py311']
required-version = '23.3.0'
exclude = '''
(
  \.venv
  | \.git
  | \.data
)
'''

[tool.mypy]
mypy_path = "merriam_api_parser"
files = ['merriam_api_parser']
python_version = "3.11"
warn_unused_configs = true
check_untyped_defs = true

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "unsubscriptable-object",
  "too-few-public-methods",
  "line-too-long",
  # Raise if has todo
  "fixme",
]
