[project]
name = 'merriam_api_parser'
description = "A Python library for parsing Merriam-Webster's Dictionary API responses."
requires-python = '==3.11'
dynamic = ['version']
readme = "README.md"
license = { file = "LICENSE" }
dependencies = []

[tool.ruff]
line-length = 88
update-check = false
target-version = "py311"
fix = true
unfixable = []
select = ["E", "F"]
ignore = []
fixable = [
  "A",
  "B",
  "D",
  "E",
  "F",
  "G",
  "I",
  "N",
  "Q",
  "S",
  "W",
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "DJ",
  "DTZ",
  "EM",
  "ERA",
  "EXE",
  "FBT",
  "ICN",
  "INP",
  "ISC",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TCH",
  "TID",
  "TRY",
  "UP",
  "YTT",
]
exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", "venv"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.black]
target-version = ['py311']
required-version = '23.3.0'
exclude = '''
(
  \.venv
  | \.git
  | setup.py
)
'''

[tool.mypy]
files = ['merriam_api']
python_version = "3.11"
warn_unused_configs = true
check-untyped-defs = true
