# https://github.com/pandas-dev/pandas/blob/main/.github/workflows/autoupdate-pre-commit-config.yml
name: "Update pre-commit config"

on:
  schedule:
    - cron: "0 7 * * *" # every day at 7am UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-pre-commit:
    permissions:
      contents: write # for technote-space/create-pr-action to push code
      pull-requests: write # for technote-space/create-pr-action to create a PR
    if: github.repository_owner == 'luke396'
    name: Autoupdate pre-commit config
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Update pre-commit config packages
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXECUTE_COMMANDS: |
            pip install pre-commit
            pre-commit autoupdate || (exit 0);
            pre-commit run -a || (exit 0);
          COMMIT_MESSAGE: "⬆️ UPGRADE: Autoupdate pre-commit config"
          PR_BRANCH_NAME: "pre-commit-config-update-${PR_ID}"
          PR_TITLE: "⬆️ UPGRADE: Autoupdate pre-commit config"
