name: "Run pre-commit"
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.11
        uses: actions/setup-python@master
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add environment variables
        env:
          MERRIAM_WEBSTER_DICTIONARY_KEY: ${{ secrets.MERRIAM_WEBSTER_DICTIONARY_KEY }}
          SOURCERY_TOKEN: ${{secrets.SOURCERY_TOKEN}}
        run: |
          if [ -z "$sourcery_token" ]; then
            echo "SOURCERY_TOKEN is either unset or empty"
          else
            echo "SOURCERY_TOKEN is set and not empty"
          fi

          sourcery login --token SOURCERY_TOKEN

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --verbose --all-files
